"""Parse Basketball Monster Excel exports into the normalized projection schema.

Basketball Monster's rankings, projections and weekly projections pages all export the same
family of ``.xls`` files (generated by MyXls, readable with ``xlrd``). Two layouts exist:

* totals: columns ``g, m, p, 3, r, a, s, b, fg%, fga, ft%, fta, to`` plus value columns
  ``pV, 3V, ...`` (their z-scores) and metadata such as ``Rank, Round, Value, Y!%, Inj, Depth``.
* per game: the same stats suffixed ``/g`` (``p/g, 3/g, ... m/g``) with ``g`` still present.

Per-game files are converted to totals by multiplying by games. Makes are rebuilt from attempts
and percentage (``fgm = fga * fg%``).
"""

from __future__ import annotations

import re
from datetime import UTC, date, datetime
from pathlib import Path

import pandas as pd

from ...projections.schema import STAT_COLS, Horizon, ProjectionSet, split_positions

TOTALS_MAP = {
    "p": "pts",
    "3": "threes",
    "r": "reb",
    "a": "ast",
    "s": "stl",
    "b": "blk",
    "to": "tov",
    "fga": "fga",
    "fta": "fta",
    "g": "games",
    "m": "minutes",
}
PER_GAME_MAP = {
    "p/g": "pts",
    "3/g": "threes",
    "r/g": "reb",
    "a/g": "ast",
    "s/g": "stl",
    "b/g": "blk",
    "to/g": "tov",
    "fga/g": "fga",
    "fta/g": "fta",
    "m/g": "minutes",
    "g": "games",
}
EXTRA_MAP = {
    "Rank": "bbm_rank",
    "Round": "bbm_round",
    "Value": "bbm_value",
    "BalV": "bbm_balanced_value",
    "ValueCG": "bbm_value_cg",
    "Y!%": "yahoo_owned_pct",
    "Adv%": "bbm_adv_pct",
    "Inj": "injury",
    "Depth": "depth",
    "QG": "quality_games",
    "b2b": "back_to_backs",
    "Ease": "schedule_ease",
    "Own": "owner",
}
VALUE_MAP = {
    "pV": "bbm_z_pts",
    "3V": "bbm_z_threes",
    "rV": "bbm_z_reb",
    "aV": "bbm_z_ast",
    "sV": "bbm_z_stl",
    "bV": "bbm_z_blk",
    "fg%V": "bbm_z_fg_pct",
    "ft%V": "bbm_z_ft_pct",
    "toV": "bbm_z_tov",
}
PER_GAME_MARKER = "p/g"


def read_bbm_export(path: str | Path) -> pd.DataFrame:
    """Read the first sheet of a Basketball Monster export as-is."""
    return pd.read_excel(path, sheet_name=0)


def is_per_game(raw: pd.DataFrame) -> bool:
    return PER_GAME_MARKER in raw.columns


def normalize_bbm(raw: pd.DataFrame) -> pd.DataFrame:
    """Convert a raw export DataFrame to the normalized schema (totals over the horizon)."""
    per_game = is_per_game(raw)
    stat_map = PER_GAME_MAP if per_game else TOTALS_MAP
    required = set(stat_map) | {"Name", "Pos", "fg%", "ft%"}
    missing = sorted(required - set(raw.columns))
    if missing:
        raise ValueError(f"not a Basketball Monster export, missing columns: {missing}")

    out = pd.DataFrame(index=raw.index)
    out["player"] = raw["Name"].astype(str).str.strip()
    out["team"] = raw["Team"].fillna("FA").astype(str).str.strip() if "Team" in raw else "FA"
    out["positions"] = (
        raw["Pos"].astype(str).str.strip().map(lambda p: "/".join(split_positions(p)))
    )
    for src, dst in stat_map.items():
        out[dst] = pd.to_numeric(raw[src], errors="coerce").fillna(0.0).astype(float)
    fg_pct = pd.to_numeric(raw["fg%"], errors="coerce").fillna(0.0)
    ft_pct = pd.to_numeric(raw["ft%"], errors="coerce").fillna(0.0)
    out["fgm"] = out["fga"] * fg_pct
    out["ftm"] = out["fta"] * ft_pct

    if per_game:
        for col in STAT_COLS + ("minutes",):
            out[col] = out[col] * out["games"]

    for src, dst in {**EXTRA_MAP, **VALUE_MAP}.items():
        if src in raw.columns:
            out[dst] = raw[src]
    if "injury" in out:
        out["injury"] = out["injury"].where(out["injury"].notna(), None)

    out.index = pd.Index(_player_ids(out), name="player_id")
    return out


def _player_ids(df: pd.DataFrame) -> list[str]:
    """Stable ids from names; duplicate names get the team appended."""
    slugs = df["player"].map(slugify)
    counts = slugs.value_counts()
    ids = []
    for slug, team in zip(slugs, df["team"], strict=True):
        ids.append(slug if counts[slug] == 1 else f"{slug}-{slugify(team)}")
    return ids


def slugify(name: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "-", str(name).lower()).strip("-")
    return cleaned or "unknown"


def load_bbm_export(
    path: str | Path,
    horizon: Horizon,
    label: str | None = None,
    as_of: datetime | None = None,
    start: date | None = None,
    end: date | None = None,
) -> ProjectionSet:
    """Read and normalize one export file into a :class:`ProjectionSet`."""
    path = Path(path)
    raw = read_bbm_export(path)
    df = normalize_bbm(raw)
    if as_of is None:
        as_of = datetime.fromtimestamp(path.stat().st_mtime, tz=UTC)
    if label is None:
        kind = "per-game" if is_per_game(raw) else "totals"
        label = f"BBM {horizon} ({kind}) {path.name}"
    return ProjectionSet(
        source="bbm", label=label, horizon=horizon, as_of=as_of, df=df, start=start, end=end
    )
